#!/bin/bash
### BEGIN INIT INFO
# Provides:          ilServer
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start ilServer instances
# Description:       Debian init script for starting ilServer instances
### END INIT INFO

JAVABIN=/usr/bin/java
ILIASDIR=/var/www/html/ilias            # Type in the root directory of your ILIAS installation
IL_SERVER_INI=/var/www/html/ilias/Services/WebServices/RPC/lib/ilServer.ini  # Type in the path to your ilserver.ini

case "$1" in
    start)
    echo "Starting ILIAS Java-Server"
        $JAVABIN -Dfile.encoding=UTF-8 -jar $ILIASDIR/Services/WebServices/RPC/lib/ilServer.jar $IL_SERVER_INI start & 
    ;;

    stop)
        echo "Shutting down ILIAS Java-Server"
        $JAVABIN -jar $ILIASDIR/Services/WebServices/RPC/lib/ilServer.jar $IL_SERVER_INI stop &
        ;;

    status)
        $JAVABIN -jar $ILIASDIR/Services/WebServices/RPC/lib/ilServer.jar $IL_SERVER_INI status &
        ;;

    restart)
        $0 stop
        sleep 2
        $0 start
        ;;

    *)
        echo "Usage: $0 {start|stop|status|restart}"
        exit 1
esac

exit 0
